import { test, expect } from '@playwright/test';

test.describe('EcoTable End-to-End Tests', () => {

  test.beforeEach(async ({ page }) => {
    // Navigate to the app root
    await page.goto('/');
  });

  test('User Signup and Login Flow', async ({ page }) => {
    // Initial state: Auth Screen (Login)
    await expect(page.getByText('Welcome Back')).toBeVisible();

    // 1. Signup Flow
    // Toggle to Sign Up
    await page.click('button:has-text("Sign Up")');
    await expect(page.getByText('Create Account')).toBeVisible();

    // Fill Signup Form
    const uniqueId = Date.now();
    const name = `Test User ${uniqueId}`;
    const email = `user${uniqueId}@example.com`;
    
    await page.fill('#signup-name', name);
    await page.fill('#signup-email', email);
    await page.fill('#signup-password', 'password123');
    
    // Submit
    await page.click('button:has-text("Create Account")');

    // Should be redirected to Dashboard
    await expect(page.getByText('Welcome back,')).toBeVisible();
    await expect(page.getByText(name.split(' ')[0])).toBeVisible();

    // 2. Logout Flow
    // Navigate to profile (Using desktop sidebar link for reliability)
    await page.click('a[href="#/profile"]');
    
    // Click Log Out
    await page.click('button:has-text("Log Out")');
    
    // Verify back to Login screen
    await expect(page.getByText('Welcome Back')).toBeVisible();

    // 3. Login Flow
    await page.fill('#login-email', email);
    await page.fill('#login-password', 'password123');
    await page.click('button:has-text("Log In")');

    // Verify back on Dashboard
    await expect(page.getByText('Welcome back,')).toBeVisible();
  });

  test('Inventory Management and Donation Flow', async ({ page }) => {
    // Quick Login using Demo Shortcut
    await page.click('button:has-text("demo@ecotable.dev")');
    await page.click('button:has-text("Log In")');
    await expect(page.getByText('Welcome back,')).toBeVisible();

    // 1. Add Item to Inventory
    await page.click('a[href="#/inventory"]');
    await page.click('button[aria-label="Manually add food item"]');

    const itemName = `E2E Item ${Date.now()}`;
    await page.fill('#itemName', itemName);
    // Select Category
    await page.click('button:has-text("Produce")');
    // Set Quantity
    await page.fill('#quantity', '5');
    await page.selectOption('#unit', 'pcs');
    
    // Set expiry to tomorrow
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    const dateStr = tomorrow.toISOString().split('T')[0];
    await page.fill('#expiryDate', dateStr);
    
    // Submit
    await page.click('button:has-text("Add to Inventory")');
    
    // Verify item added to list
    await expect(page.getByText(itemName)).toBeVisible();

    // 2. Donate the Item
    // Search for the item to ensure visibility
    await page.fill('input[placeholder="Search food items..."]', itemName);
    
    // Click "Donate" button on the specific card
    await page.click('button[aria-label="Donate Item"]');

    // Donation Step 1: Selection (Item should be pre-selected)
    await expect(page.getByText('Select Items to Donate')).toBeVisible();
    // Verify we can proceed
    await page.click('button:has-text("Continue")');

    // Donation Step 2: Choose Recipient
    await expect(page.getByText('Choose Recipient')).toBeVisible();
    // Select the first available NGO in the list
    await page.locator('div[role="radio"]').first().click();
    await page.click('button:has-text("Continue")');

    // Donation Step 3: Logistics
    await expect(page.getByText('Coordinate Handover')).toBeVisible();
    await page.fill('input[type="tel"]', '555-0000');
    // Fill Date/Time
    await page.fill('input[type="date"]', dateStr);
    await page.fill('input[type="time"]', '12:00');
    
    // Confirm
    await page.click('button:has-text("Confirm Donation")');

    // Donation Step 4: Success
    await expect(page.getByText('Request Sent!')).toBeVisible();
    await expect(page.getByText('Return to Dashboard')).toBeVisible();
  });

  test('Recipe Generation Flow', async ({ page }) => {
    // Intercept and mock Gemini API calls to avoid cost/flakiness
    await page.route('**/models/gemini-3-flash-preview:generateContent**', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          candidates: [{
            content: {
              parts: [{
                text: JSON.stringify([
                  {
                    title: 'E2E Mock Recipe',
                    description: 'A test recipe generated by Playwright mock.',
                    ingredients: ['Ingredient A', 'Ingredient B'],
                    instructions: ['Step 1: Mix.', 'Step 2: Cook.'],
                    cookingTime: 15,
                    difficulty: 'Easy',
                    savedItems: ['Ingredient A']
                  }
                ])
              }]
            }
          }]
        })
      });
    });

    // Login
    await page.click('button:has-text("demo@ecotable.dev")');
    await page.click('button:has-text("Log In")');

    // Go to Recipes
    await page.click('a[href="#/recipes"]');
    
    // Input ingredients
    await page.fill('input[placeholder*="Enter ingredients"]', 'Ingredient A');
    
    // Generate
    await page.click('button[aria-label="Generate Recipes"]');

    // Verify Result Card Appears
    await expect(page.getByText('E2E Mock Recipe')).toBeVisible();
    await expect(page.getByText('15 mins')).toBeVisible();
    await expect(page.getByText('A test recipe generated by Playwright mock.')).toBeVisible();
  });

});